<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_guest_arrival_tests.TestGuestArrival-20240401104642" tests="20" file="test_guest_arrival_tests.py" time="0.165" timestamp="2024-04-01T10:46:43" failures="3" errors="3" skipped="0">
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc10DUP" time="0.004" timestamp="2024-04-01T10:46:42"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc11DEL" time="0.003" timestamp="2024-04-01T10:46:42"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc12DUP" time="0.003" timestamp="2024-04-01T10:46:42"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc12MOD" time="0.004" timestamp="2024-04-01T10:46:42"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc13" time="0.003" timestamp="2024-04-01T10:46:42"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc14" time="0.004" timestamp="2024-04-01T10:46:42"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc16" time="0.004" timestamp="2024-04-01T10:46:42"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc2" time="0.003" timestamp="2024-04-01T10:46:42"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc3" time="0.002" timestamp="2024-04-01T10:46:42"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc4" time="0.002" timestamp="2024-04-01T10:46:42"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc5" time="0.003" timestamp="2024-04-01T10:46:42"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc7F1DEL" time="0.003" timestamp="2024-04-01T10:46:43"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc9DUP" time="0.002" timestamp="2024-04-01T10:46:43"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc9MOD" time="0.003" timestamp="2024-04-01T10:46:43"/>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc15" time="0.008" timestamp="2024-04-01T10:46:42">
		<failure type="AssertionError" message="&quot;'Localizer' is not well defined&quot; != &quot;'Id' key missing in JSON&quot;
- 'Localizer' is not well defined
+ 'Id' key missing in JSON
"><![CDATA[Traceback (most recent call last):
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "c:\users\izans\g88.2024.t05.ge2\src\unittest\python\test_guest_arrival_tests.py", line 326, in testTc15
    self.assertEqual(str(exception), "'Id' key missing in JSON")
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: "'Localizer' is not well defined" != "'Id' key missing in JSON"
- 'Localizer' is not well defined
+ 'Id' key missing in JSON

]]></failure>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc17" time="0.007" timestamp="2024-04-01T10:46:42">
		<failure type="AssertionError" message="&quot;'Localizer' is not well defined&quot; != 'new IdCard is not in reservation'
- 'Localizer' is not well defined
+ new IdCard is not in reservation
"><![CDATA[Traceback (most recent call last):
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "c:\users\izans\g88.2024.t05.ge2\src\unittest\python\test_guest_arrival_tests.py", line 366, in testTc17
    self.assertEqual(str(exception), "new IdCard is not in reservation")
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: "'Localizer' is not well defined" != 'new IdCard is not in reservation'
- 'Localizer' is not well defined
+ new IdCard is not in reservation

]]></failure>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc7F2DEL" time="0.006" timestamp="2024-04-01T10:46:43">
		<failure type="AssertionError" message="&quot;'Localizer' is not well defined&quot; != &quot;'Id' key missing in JSON&quot;
- 'Localizer' is not well defined
+ 'Id' key missing in JSON
"><![CDATA[Traceback (most recent call last):
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "c:\users\izans\g88.2024.t05.ge2\src\unittest\python\test_guest_arrival_tests.py", line 139, in testTc7F2DEL
    self.assertEqual(str(exception), "'Id' key missing in JSON")
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: "'Localizer' is not well defined" != "'Id' key missing in JSON"
- 'Localizer' is not well defined
+ 'Id' key missing in JSON

]]></failure>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc1Valid" time="0.065" timestamp="2024-04-01T10:46:42">
		<error type="hotelManagementException" message="'Localizer' is not well defined"><![CDATA[Traceback (most recent call last):
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Users\izans\G88.2024.T05.GE2\venv\lib\site-packages\freezegun\api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\izans\g88.2024.t05.ge2\src\unittest\python\test_guest_arrival_tests.py", line 19, in testTc1Valid
    value = myManager.guestArrival(filepath)
  File "c:\users\izans\g88.2024.t05.ge2\src\main\python\UC3MTravel\HotelManager.py", line 219, in guestArrival
    raise hotelManagementException("'Localizer' is not well defined")
UC3MTravel.HotelManagementException.hotelManagementException: 'Localizer' is not well defined
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc6" time="0.017" timestamp="2024-04-01T10:46:42">
		<error type="hotelManagementException" message="'Localizer' is not well defined"><![CDATA[Traceback (most recent call last):
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Users\izans\G88.2024.T05.GE2\venv\lib\site-packages\freezegun\api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\izans\g88.2024.t05.ge2\src\unittest\python\test_guest_arrival_tests.py", line 100, in testTc6
    value = myManager.guestArrival(filePath)
  File "c:\users\izans\g88.2024.t05.ge2\src\main\python\UC3MTravel\HotelManager.py", line 219, in guestArrival
    raise hotelManagementException("'Localizer' is not well defined")
UC3MTravel.HotelManagementException.hotelManagementException: 'Localizer' is not well defined
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestGuestArrival" name="testTc8F1DUP" time="0.018" timestamp="2024-04-01T10:46:43">
		<error type="hotelManagementException" message="'Localizer' is not well defined"><![CDATA[Traceback (most recent call last):
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Users\izans\G88.2024.T05.GE2\venv\lib\site-packages\freezegun\api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\izans\g88.2024.t05.ge2\src\unittest\python\test_guest_arrival_tests.py", line 148, in testTc8F1DUP
    value = myManager.guestArrival(fileName)
  File "c:\users\izans\g88.2024.t05.ge2\src\main\python\UC3MTravel\HotelManager.py", line 219, in guestArrival
    raise hotelManagementException("'Localizer' is not well defined")
UC3MTravel.HotelManagementException.hotelManagementException: 'Localizer' is not well defined
]]></error>
	</testcase>
</testsuite>
